version: '3.2'
services:
    ###########################################
    #   Setup node container
    ###########################################
    build: ./backend
    expose: 
        - 5000
    environment: 
        API_HOST: http://localhost:5000
        APP_SERVICE_PORT: 5000
    ports: 
        - 5000:5000
    volumes: 
        - ./backend/src:/app
    command: npm run start


###########################################
#   Setup client container
###########################################
client:
    build: ./client
    environment: 
        REACT_APP_PORT: 3000
    expose: 
        - 3000
    ports: : 
        - 3000:3000
    volumes: 
        - ./client/src:/app
    links: 
        - server
    command: npm run start



